### ISSUE TITLE
Maze should be able to switch response type

### ISSUE THREAD

**Issue by foikila** [dbwebb-se/linux#2]
Maze should deliver html and CSV as a alternative to json a response.
The users should be able to change the response with an query-param named type.
This should give html: `/1/maze/0?type=html`
This should give CSV: `/1/maze/0?type=csv`

[CSV](https://en.wikipedia.org/wiki/Comma-separated_values)

**Comment by mosbth** [comment]
Where do we stand on this? Do or dont?

**Comment by foikila** [comment]
It's partly implemented already. The `csv`-part is done but not the `html`-part.

**Comment by mosbth** [comment]
So, should we close this, leaving html for another day?

**Comment by mosbth** [comment]
I'll close it and leave html for another day.
