### ISSUE TITLE
Maze - Should be more consistent

### ISSUE THREAD

**Issue by litemerafrukt** [dbwebb-se/linux#7]
If you try to enter the maze before you selected a map you get an answer with:
`text: "Map not selected"`  and response code 500.
Would be more consistent with other errors if changed from "text" to "error".

**Comment by foikila** [comment]
Na, its more like "error" is the "index" that should be changed instead, regards to consistency. Its only used two times throughout the hole program: https://github.com/mosbth/linux/blob/master/example/nodejs/maze/maze.js#L269-L280

**Comment by litemerafrukt** [comment]
Ok :smile:

**Comment by foikila** [comment]
But we can change the "error" to "text" instead.

**Comment by litemerafrukt** [comment]
For consistency change response type to `'plain'` on:
https://github.com/mosbth/linux/blob/master/example/nodejs/maze/maze.js#L225

**Comment by mosbth** [comment]
I'll fix that.
